### PR TITLE
Feature/be 20

### PR DESCRIPTION
**Pull request by BElifb**
* Researched and decided to use **django-mptt** for comments. This helps us with managing hierarchical data. Here's the [documentation](https://django-mptt.readthedocs.io/en/latest/overview.html). There are useful tags for managing data with django template tags (indentation etc.), but if it is not compatible with react we can always manually use the fields.
* Updated Comment model accordingly.
* Created 2 API endpoints with 5 APIs in total.
* Documented in detail with Swagger. Here's a preview.
image
* Tested with both Postman and Swagger.
* Since the Comment model is updated, you may wanna delete previous migrations, clean the database and then migrate again to avoid getting errors.
* Don't forget to reinstall requirements (django-mptt).

### CODE REVIEW

**Comment by KarahanS** [comment]
As we talked in the [meeting](https://github.com/bounswe/bounswe2022group8/wiki/Week-7-BE-Meeting-%233-(15.11.2022)), making a comment requires authentication. I'm marking this PR as `in progress` for now and waiting for you to update the relevant API so that it requires authentication token.

**Comment by BElifb** [comment]
Previously all requests required authentication including GET, removed authentication requirement from GET requests for individual and all art item comments. Tested it through swagger. It should be good to go now.

**Comment by BElifb** [comment]
* Solved merge conflicts with master.

**Comment by KarahanS** [comment]
Reviewed the functionality carefully. Let me provide my foundings and improvements:
* When I attempted to get the comments on a non-existing art item, it failed (`500` Internal Server Error) with the following error description: `api.models.artitem.ArtItem.DoesNotExist: ArtItem matching query does not exist.` It was because we were not checking if the given artitem ID is present in the database or not - so I added a single try-except block to verify that. Also updated the documentation. If given artitem ID is not present, it returns `404` Not Found.
* There were some `print` statements in the code. Most probably you used for debugging, I removed them.
* In the URL paths, we used the terms `id` and `artitemid` interchangeably at some points which were confusing. I fixed that confusion to improve consistency.
* Apart from those, I wonder why we are using URLs like `http://127.0.0.1:8000/api/v1/artitems/<artitemid>/comments/<int>/` rather than directly using `http://127.0.0.1:8000/api/v1/artitems/comments/<int>/`. Initially, I thought IDs of the comments were dependent on the art items - meaning that there could be 2 comments with same IDs - but on different art items. However, after some testing I found out that this is not the case. Do I miss something here or can we just call these APIs without providing the `artitem` IDs?

If I miss something, you can just leave an answer and merge the PR. Otherwise, I think it's better to get rid of `artitemid` parts from some of the URLs.
Apart from that, thanks for this detailed work. I was wondering how we could come up with a solution for "recursive" comment system and it seems that we solved it. Thanks!

**Comment by BElifb** [comment]
> [At Google,] there is virtually no difference [between flat URLs and hierarchical URLs] … It can be very helpful for users if you have subdirectories … [Organizing content within subdirectories] can be a great thing for usability, and I definitely recommend having your site categorized like that … Having one or two extra directories [in your URLs is] not a major factor in Google’s search engine rankings.
* You're right we're not directly using artitemid in one of the endpoints. But I think it is better for UX to include the hierarchical path, one might even argue we add the user to the url as well. I don't think at this point it is disturbingly long. Let me know if you disagree @KarahanS 
* Thanks for the update about other things, using artitemid and id interchangingly must have been confusing.

**Comment by KarahanS** [comment]
I'm totally ok with the URL structure. Merging the PR since there is no further action required here.

**Pull request merged**
