### PR TITLE
Feature/BE-35: Art Item Category

### PR DESCRIPTION
**Pull request by BElifb**
* Renamed **type** field of ArtItem model as **category**.
* Created predefined choices for category. Updated model class.
* Updated serializer and swagger documentation.
* Tested through admin site and swagger.
* Currently ArtItem APIs are operating with 2 character codes of the categories. Such as; 
  * `{
  "id": 5,
  "owner": {
    "id": 2,
    "username": "string",
    "name": "st",
    "surname": "ring",
    "profile_path": "avatar/default.png"
  },
  "title": "newartitem",
  "description": "good stuff",
  "category": "PR",
  "tags": [],
  "artitem_path": "artitem/defaultart.jpg",
  "likes": 0,
  "created_at": "2022-12-16T23:25:43.904293Z",
  "isLiked": false
}`
  * Where codes are as following:

>   ARCHITECTURE = 'AR', _('Architecture')
>         SCULPTURE = 'SC', _('Sculpture')
>         DRAWING = 'DR', _('Drawing')
>         PHOTOGRAPHY = 'PH', _('Photography')
>         PRINTS = 'PR', _('Prints')
>         PAINTING_ACRYLIC = 'PA', _('Painting/Acrylic')
>         PAINTING_OILPAINT = 'PO', _("Painting Oilpaint")
>         PAINTING_WATERCOLOUR = 'PW', _("Painting Watercolour")
>         PAINTING_DIGITAL = 'PD', _("Painting Digital")
>         PAINTING_MURAL = 'PM', _("Painting Mural")
>         PAINTING_GOUACHE = 'PG', _("Painting Gouache")
>         PAINTING_PASTEL = 'PP', _("Painting Pastel")
>         PAINTING_ENCAUSTIC = 'PE', _("Painting Encaustic")
>         PAINTING_FRESCO = 'PF', _("Painting Fresco")
>         PAINTING_SPRAY = 'PS', _("Painting Spray")
>         PAINTING_OTHER = 'OP', _("Painting Other")
>         OTHER = 'OT', _("Other")
  * It is easy enough switching to communicating with human readable formats of the categories ("Other" instead of "OT" ). Frontend let me know which you prefer @kostanya

### CODE REVIEW

**Comment by KarahanS** [comment]
Looks great! Maybe we could update the documentation as well, stating that input `type` should be one of the predefined values, otherwise it'll give an error @BElifb.

**Review by KarahanS — DISMISSED** [review]

**Comment by BElifb** [comment]
* I just tested `artitems/me/upload` API with the following input;
  * `{
  "title": "Portrait of Joel Miller",
  "description": "Joel Miller from TLOU universe.",
  "category": "PW",
  "tags": [
  ],
  "artitem_image": "base64 string"
}` (not included image encoding here to avoid clutter)
* I was able to see _Painting Watercolour_ as the category in the admin site as expected. Could you specify what went wrong and with which API endpoint? @KarahanS

**Comment by KarahanS** [comment]
Now I got it, you have changed the name of the field from `type` to `description` but it's still shown as `type` in our Swagger documentation. I was trying it with `type`, that's why I was not able to change it. Could you please fix the docs? Then I'll approve immediately.

**Comment by KarahanS** [comment]
@kostanya We change the field name `type` to `category` for artitems btw. You may need to update some API calls accordingly.

**Review by KarahanS — APPROVED** [review]

**Comment by kostanya** [comment]
@KarahanS I'll make modifications accordingly.

**Pull request merged**
