### PR TITLE
Bugfix/FE-19

### PR DESCRIPTION
**Pull request by sinemKocoglu**
As we discussed before in #376 , bug in displaying annotation body is fixed by changes on the format in backend. Also, from now on a user can edit and delete only her own annotations. In image annotation, user can see other users' annotations in read only mode. In text annotation, editor looks like it allows editing and deleting other users' annotations but it does not do it. When you click again on text annotation, you can see no difference. Annotation is completed!

### CODE REVIEW

**Comment by kostanya** [comment]
Great great news! Thank you so much for your amazing efforts @KarahanS @sinemKocoglu.

**Comment by KarahanS** [comment]
Thanks for the hard work. I reviewed the improvements using Docker. Here some of the things I notice that can be improved:
* It seems like a user can edit another user's text annotation right now. I think we should apply the same logic we used for image annotation to text annotation as well to avoid that.
* We can provide a `hide annotation` button for text annotations as well. Also, we can actually create a box with the body of the annotation and the owner (exactly what you did for image annotations) for text annotations as well so that one understands who dropped the note. (If it is possible, best way is to add the user's name directly to the box generated by the Annotorious - but I don't know if it'll take so much effort).
* Lastly, we have to get rid of that `Reply` section somehow. I think this is not urgent, so don't let this block you for now. First two ones seem to be more important.

**Comment by sinemKocoglu** [comment]
3 statements are solved and checked on discord with @KarahanS .

**Comment by KarahanS** [comment]
Reviewed and made the necessary updates on annotation models to fix the aforementioned problems with @sinemKocoglu. Ready to merge.

**Review by KarahanS — APPROVED** [review]

**Comment by sinemKocoglu** [comment]
Fixed the last bug related to read only mode of text annotations. Actions for annotations are tested manually. Everything works as desired. Just a reminder, when you click on a text annotation of another user, click on close button before creating your own text annotation for better practice. Thanks @KarahanS for all support and effort. Merging directly.

**Pull request merged**
