### PR TITLE
Feature/BE-4

### PR DESCRIPTION
**Pull request by BElifb**
* Please clean your database and delete any previous migrations you may have, since extending the AbstractUser will change the whole database schema.
* Created User class by extending AbstractUser, also created Tag, ArtItem and Comment classes.
* Added AUTH_USER_MODEL to settings.py. Also, prefer to create foreign keys to the User model importing the settings from django.conf import settings and referring to the settings.AUTH_USER_MODEL instead of referring directly to the custom User model. 
* Installed Pillow package for the media files and updated requirements.txt with the latest additions.
* Configured MEDIA_ROOT in settings.py and added MEDIA folder with default images.
*  Created serializers for the models.
* Created a decorator to check whether the user is active_user or not.  There are some things to keep in mind here:
  *  Current redirection path for the decorator is 'login', but we can configure this later as the project structure is more defined.
  * is_active and is_active_user are two seperate concepts. First refers to user's account not being blocked (we'll use this when there are complaints about the account and the admin/moderator decides to ban the user), second (is_active_user) refers to user having a level 2 acoount.
* Created and configured the admin site.
* Tested creating users via admin site, fixed media root. 
* Please refer to the #187  for further information

### CODE REVIEW

**Comment by KarahanS** [comment]
Could you have a look at my comment about settings in #187?

**Comment by BElifb** [comment]
* Created basic homepage.
* Added base and index templates to newly created folder in API app.
* Added redirection to admin site.

**Comment by KarahanS** [comment]
Looks good to me. Right now, `media` doesn't seem to have any functionality (Django handles the images I guess) - but it will be useful when we want to receive an image from Frontend in base-64 encoded version, decode it and save it in the `media`  folder.

**Comment by KarahanS** [comment]
I re-configured the settings folder to include both development and production settings. Can I kindly request you to move your `.env` file to the `settings` folder and run the application to see if everything is working properly? (It's working on my side but let's make sure that it's working in general).
I'm taking the PR to `Review needed`, however you can merge it directly if you confirm that new settings is working properly.

**Comment by BElifb** [comment]
* Profile images in the Media folder were giving an error. I updated the BASE_DIR in base.py, since the depth of folders has increased. Everything seems to be working now. You can check it a final time @KarahanS , otherwise I'm merging it to master.

**Comment by KarahanS** [comment]
LGTM

**Pull request merged**
