### PR TITLE
html templates are created.

### PR DESCRIPTION
**Pull request by sinemKocoglu**
I have created html templates for comment functions. Necessary paths and views are added to django_app folder. You can test html pages on webpage.

**Templates:**

- comments_of_artitem.html
- post_comment_on_artitem.html
- delete_comment.html

I think there is no conflict, but review is needed.

### CODE REVIEW

**Comment by KarahanS** [comment]
During our meeting with @mumcusena, we found out that HTML templates for ```DELETE``` request was not working. We fixed it by adding the CSRF token to the parameters of the fetch in Javascript. Related [commit](https://github.com/bounswe/bounswe2022group8/pull/130/commits/28dfca5da8f444765f8a06414645dbf7ec9b711d). Can I kindly remind you to test your frontend once more for other functionalities as well? Thanks in advance.

**Comment by sinemKocoglu** [comment]
I have tested all the comment functionalties in frontend. They all work well. Thanks for your contribution. Could you please merge pr if there is no other error?

**Comment by KarahanS** [comment]
Tested again both running the tests and via frontend. Works properly.

**Comment by KarahanS** [comment]
After merging I've deleted ```template/comment``` branch in the remote repository (here in this repo). 
In order to delete it from local, you can follow these steps:
i) Delete the local branch using ```git branch -d template/comment```. After this step, if you see that ```remotes/origin/model1``` still exists, then do the following.
ii) Delete the remote branch that doesn't have any correspondence in remote repository: ```git fetch --prune```

**Pull request merged**
