### PR TITLE
Feature/BE-40: Recommendation System

### PR DESCRIPTION
**Pull request by BElifb**
* Added popularity field and updatePopularity function for ArtItem.
* Created exhibition history.
* Added number_of_views and popularity fields to Exhibition, created updatePopularity function.
* Added popularity field and updatePopularity function for User.
* Created UserInterest model to keep track of user interests (category based), created updateFirstThree and updateInterest functions.
* Called these functions in necessary places to update popularities and interests.
*  Created signals and connected in necessary places to initiate UserInterest creation at user creation.
* Updated history model and related receiver to overcome traversing GenericForeignKey problem.
* Created 6 API endpoints for recommendation:
image
* Tested everything through admin site and Postman.
* Created detailed swagger documentation for APIs.

### CODE REVIEW

**Comment by BElifb** [comment]
## Algorithm Details and Parameters

* `ArtItem popularity` is calculated taking into account; **number_of_views** of the artitem, number of **likes** and its creation **date**. The date parameter is added to age the popularity as time goes by, so that user always get recommended the freshest content.

* `User popularity` is calculated taking into account; **number of follwers** of the user, **number of art items** that the user has and the **number of exhibitions** they have. 

* `Exhibition popularity` is calculated taking into account the **number of views** the exhibition has and its creation **date**. The date parameter is added to age the popularity as time goes by, so that user always get recommended the freshest content.

* `User Interest `is calculated in a _category based_ manner. Everytime the user interacts with content from that category, the users interest score in that category is updated. This interaction can be in various forms such as **liking**, **viewing** or **uploading** an art item in that category. These all affect in varying degrees, and  among these interests top 3 are selected for recommendation.

### Recommendation Functions
* Recommendation functions (APIs) make use of these parameters.
  * For instance art item recommendation function recommends to user art items in  user's top 3 favourite categories, that the user has never seen before. And inside these categories it ranks the items according to popularity and recommends the most popular ones. Popularity of items are everchanging as more users interact with them and as time goes by (aging), so that with enough activity on the website users will get fresh recommendations. We can also consider introducing more randomness to the system in the future.
  
  * Exhibition and User recommendation functions operate in similar ways. (Using not following condition for user reco instead of being never seen). For more detail please refer to the swagger documentation.
  
  * Anonymous versions of functions mostly make use of the popularity and don't specifically cater to user interests. Again refer to swagger for more detail.

**Comment by KarahanS** [comment]
Thank you for this excellent work, much appreciated! @BElifb 
While reviewing the code, I've come up with the following question:
* Why do we separate routes of anonymous user and registered user cases? We can simple check it within an `if-else` statement and act accordingly. By doing so, we'll also make the work of frontend easier as they won't have to check if the user is anonymous or not at the front side.

**Comment by BElifb** [comment]
* Thank  you for your review @KarahanS 
* I combined anonymous endpoints as recommended, but I think frontend still needs to check, because if they send an erroneous token instead of not sending one at all, it throws an error.
* While testing I fixed a small mistake that led to items appearing twice if there wasn't enough in the database.

**Comment by KarahanS** [comment]
Updated urls to be:
* ```recommendations/artitems/```
* ```recommendations/exhibitions/```
* ```recommendations/users/```

Also updated description for `401` as `Invalid Token` rather than `Authentication is required` since anonymous users are also able to use them.
One possible bug I spotted: When I call `/api/v1/exhibitions/online/1`, without any token, I get the following error:
> Cannot assign "<django.contrib.auth.models.AnonymousUser object at 0x00000218EC8F1D00>": "History.user" must be a "User" instance.
fyi @BElifb

**Comment by BElifb** [comment]
* I left the urls that way to differentiate, if we had art item recommendations in the future. But that doesn't really matter now, so I'm leaving them as is.
* Good catch with the error. Although I don't understant why the same thing doesn't throw errors in the artitem and user profile cases, I added authentication checks for all of them. So it should be good now. @KarahanS

**Comment by KarahanS** [comment]
Tested with Postman, everything seems to be working properly. Approved!

**Review by KarahanS — APPROVED** [review]

**Pull request merged**
