### PR TITLE
Feature/BE-9

### PR DESCRIPTION
**Pull request by KarahanS**
* Implemented login/logout APIs.
* Added some options for ```AUTH_PASSWORD_VALIDATORS``` to the settings. This will enable us to reject some passwords (common passwords or passwords that contain only numeric characters - easy stuff actually, it's provided by Django).
* Updated the ```Login``` API so that it can work for both email and username.
* These implementations use [Knox tokenization](https://www.django-rest-framework.org/api-guide/authentication/#django-rest-knox), which have serious questions for this: Firstly, how can we use tokenization system? Should we return the token to frontend and should they store it in cache or something? (I believe we will answer this question in a couple of days) Secondly, should we use Knox? Can we use Django authentication or Django Rest Framework authentication systems? Or maybe another third-party tool like JWT? I looked at the previous groups and saw very different practices:
   * [This group](https://github.com/bounswe/bounswe2020group2/tree/master/ecommerce/backend/API/utils) seems to have implemented their own authentication system or something that inherits ```from rest_framework.authentication import BaseAuthentication``` (wow).
   * [This group](https://github.com/bounswe/bounswe2020group5/blob/master/app/backend/bupazar/settings.py) seems to have used ```rest_framework.authentication.TokenAuthentication```.
   * There are some other groups as well using different strategies.
 * There was no password checking in the registration. I fixed that. Please review carefully folk, I might have missed something. With this PR, ```api/v1/auth/register/```,  ```api/v1/auth/login/```,  ```api/v1/auth/logout/``` should work properly. Don't forget to give Authorization token while trying out the logout functionality. Also name of the parameter should "credential", not "username" or "email" for login - keep that in mind.
 * In a way this PR is related to #199, #195, #194.

### CODE REVIEW

**Comment by KarahanS** [comment]
Additionally:
* Implemented **registeration** API. You can test it using ```http://127.0.0.1:8000/api/v1/auth/register/``` and providing raw data in the following format:
```json
{
    "password": "justification",
    "username": "on_existentialism",
    "email": "alvin.plantiga@calvin.edu",
    "password_confirm": "justification"
}
```
* Implemented a unittest regarding the username validation. (Not so important, I was just trying to remember unittests and making sure that my function is working properly).
* Please notice that in `backend/urls.py`, I added `path('api/v1/', include('api.urls'))`. This will include all references to our APIs. I think we won't need to add anything more here. We will be collecting API urls in `api/urls.py`. Therefore you need to add the route of your API to there after implementation. In practice app, we were adding website routes to `django_app/urls`, it's because we were trying to render the HTMLs from Django - now we won't do it.

**Comment by BElifb** [comment]
* Ran the unit tests, they seem OK.
* Registration API
  * When I tried to give a token to the registration api (In the headers as Authorization, like we did in login api), it gives invalid token error.
  * This is not necessarily a problem but when the email already exists, it doesn't display other errors such as username being too short. And in some other cases it prioritizes certain errors over others and doesn't display them all. 

* For login api:
  * Given {
    "password": "justification",
    "username": "..on_w"
}
Received:
{
    "credential": [
        "This field is required."
    ]
}
Don't know if this was expected behaviour. 
  * And with values expected to exist in database (double checked to see they gave error in the registration phase), received the same result.
  * When I tried giving the token via Authorization in the headers, received:
{
    "detail": "Invalid token."
}
  * Another thing to consider here is that with admin (superuser) we have the right to override password restrictions, do the checks prevent api from logging the admin in ?


* Logout api returns:
{
    "detail": "Authentication credentials were not provided."
}
  * Again don't know if I should have supplied some sort of parameter or token, since the API documentation is not complete as of now.
* Other than that Registration API seems to be working, login and logout were working the other they when we tried over online call, I am thinking I was possibly giving the parameters or the token wrong?
* Haven't tested the dockerized version of the API's yet.

**Comment by mumcusena** [comment]
* For Login API:
 The parameter name is changed to "credential" in order to support login with both email and username

* I updated the API documentation you can check your inputs and outputs from there.

I tested all endpoints they are working without any errors. You can merge the PR @KarahanS .

**Comment by KarahanS** [comment]
* Another thing to consider here is that with admin (superuser) we have the right to override password restrictions, do the checks prevent api from logging the admin in ?
> Created a super user and tested the ```aut/login/``` with the following information:
```json
{
    "password": "admin",
    "credential": "admin@hotmail.com"
}
```
It worked without any problem:
ss

**Pull request merged**
