### PR TITLE
feature/BE-28 Like Unlike APIs

### PR DESCRIPTION
**Pull request by serdarakol**
* like and unlike features for art item and comment objects are developed
* api/serializers/like.py and api/views/like.py files are created.
* necessary changes done in models/artitem.py, models/models.py, models/user.py and api/urls.py

### CODE REVIEW

**Comment by KarahanS** [comment]
As we have discusses in a previous [PR](https://github.com/bounswe/bounswe2022group8/pull/259), REST API names shouldn't have verbs - and they should be concise and clear. You should consider update the urls accordingly. For example, you can replace `users/like-artitem/<int:id>` with `artitems/like/<int:id>` or `users/like-comment/<int:id>` with `<comments/likes/<int:id>` @serdarakol.

**Comment by KarahanS** [comment]
When frontend redirects user to an art item he has liked before, they must be able to understand if that art item was liked by him. If so, they should color the `like` button or something. According to your APIs, they can do it by fetching all the liked art items of the user - which is very inefficient. Consider, adding returning a new filed `isLiked` - which is False or True according to the currently logged-in user in `GET` artitems API. It should be, by default, false if someone who is not logged-in is trying to view the art items.
If you see another way to do it, that's also ok - main point is that we have to give this information to frontend efficiently.

**Comment by KarahanS** [comment]
`ArtItem` attempts to import `User`, and `User` attempts to import `ArtItem` - which leads to circular import problem. Am I missing something here cause it doesn't run with this problem? Did you run the code successfully?

**Comment by KarahanS** [comment]
A user shouldn't be able to like their own art items or like their comments. Do we prevent it right now? Can't test the code due to the error stated above.

**Comment by KarahanS** [comment]
Updated task number to avoid conflicts. fyi

**Comment by serdarakol** [comment]
> 

I think a user should be able to like their own content. In most of the platforms users are able to like their own content but they usually don't. I was not preventing and testing it on purpose.

**Comment by KarahanS** [comment]
> > A user shouldn't be able to like their own art items or like their comments. Do we prevent it right now? Can't test the code due to the error stated above.
> 
> I think a user should be able to like their own content. In most of the platforms users are able to like their own content but they usually don't. I was not preventing and testing it on purpose.

Ok let's remind @mumcusena to update the requirements if necessary accordingly.

**Comment by KarahanS** [comment]
In Swagger, there are two tags: `like` and `Like`. I think everything related to `like` can be collected under the `like` tag.

**Comment by serdarakol** [comment]
> When frontend redirects user to an art item he has liked before, they must be able to understand if that art item was liked by him. If so, they should color the `like` button or something. According to your APIs, they can do it by fetching all the liked art items of the user - which is very inefficient. Consider, adding returning a new filed `isLiked` - which is False or True according to the currently logged-in user in `GET` artitems API. It should be, by default, false if someone who is not logged-in is trying to view the art items. If you see another way to do it, that's also ok - main point is that we have to give this information to frontend efficiently.

These APIs are implemented in the last commit

**Comment by KarahanS** [comment]
1- When a user attempts to like an art item or a comment that he has already liked, we receive an `IntegrityError`. Backend shouldn't be returning raw errors to frontend since it causes application to crash. You have to catch the `IntegrityError` and return the related HTTP Status code. You can have a look at the POST  `follow` API to learn how to do it.
2- Right now, we require frontend to send 2 requests (GET artitem and GET isLiked) to learn if the artitem is liked by the currently logged-in user. Rather than creating a new view, we could've just integrated that information to the GET artitem API. I wonder why you preferred the longer way here.
3- There was a typo in one of the url paths - I fixed it.
4- We have to return number of likes in the art item. You implemented the corresponding `property` function but didn't use it anywhere? I updated the artitem serializer accordingly so that we return the number of likes as well.

**Comment by KarahanS** [comment]
Couldn't run. Gives this error:
```
AssertionError: http method defined multiple times
```

**Comment by KarahanS** [comment]
`http://localhost:8000/api/v1/users/1/liked-artitems/` gives this error:
```
AttributeError at /api/v1/users/1/liked-artitems/
Got AttributeError when attempting to get a value for field `user` on serializer `LikeArtItemSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ArtItem` instance.
Original exception text was: 'ArtItem' object has no attribute 'user'.
```

**Comment by serdarakol** [comment]
> `http://localhost:8000/api/v1/users/1/liked-artitems/` gives this error:
> 
> ```
> AttributeError at /api/v1/users/1/liked-artitems/
> Got AttributeError when attempting to get a value for field `user` on serializer `LikeArtItemSerializer`.
> The serializer field might be named incorrectly and not match any attribute or key on the `ArtItem` instance.
> Original exception text was: 'ArtItem' object has no attribute 'user'.
> ```

this bug is fixed but testing is ongoing.

**Comment by KarahanS** [comment]
Resolved merge conflicts and tested the APIs. Everything seems working now - thanks for the effort. Merging the PR into master and closing.

**Pull request merged**
